### PR TITLE
Add deletion secret

### PR DESCRIPTION
**Pull request by jbatmalle**
---
name: Add deletion secret
about: feature
---

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] You have read the contributing guide
- [X] Tests for the changes have been added
- [ ] The documentation has been reviewed and updated as needed

## What is the current behavior?

The secret is not deleted

## What is the new behavior?

The secret is deleted

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by delineaKrehl** [comment]
@jbatmalle can you also add a secret_delete example to go along with this add?

**Review by delinea-sagar — COMMENTED** [review]
@jbatmalle can you add a secret_delete example and variable file like secret_delete.tf and secret_delete.tfvars?

**Comment by jbatmalle** [comment]
Hi @delinea-sagar  and @delineaKrehl,
Sorry for the delay
I don't quite understand what you want
Terraform manage ressource destruction and we can't create a tf file with that
The only way is to use the count directive but that won't be clear to users

**Comment by delinea-sagar** [comment]
@jbatmalle For reference, we have to provided example Terraform files, secret_delete.tf and secret_delete.tfvars, in the 'example' and 'vars' folders, respectively. User will simply copy the content of these files, replace the placeholder values with specific information, and then apply the configuration using Terraform. We have also included examples for getting and creating secrets in the 'example' and 'vars' folders.

**Comment by delinea-sagar** [comment]
@jbatmalle After executing the 'terraform destroy' command, will dataSourceSecretDelete be automatically invoked?

**Comment by jbatmalle** [comment]
Hi @delinea-sagar ,
Yes of course, when you manage your secrets using terraform, if you destroy your ressource the function will be called
These are basic terraform functions (create, update, delete) and there is no need to explain this behaviour

**Review by delinea-sagar — APPROVED** [review]

**Pull request merged**
